version: '3.5'

services:
    nginx:
        build: ./docker/nginx/
        volumes:
            - ./project/web:/var/www/web
            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./docker/nginx/sites/:/etc/nginx/sites-available
            - ./docker/nginx/conf.d/:/etc/nginx/conf.d
        depends_on:
            - php-fpm
        ports:
            - 8084:80

    php-fpm:
        build: ./docker/php-fpm/
        volumes:
            - ./project:/var/www
        expose:
            - 9000
        environment:
            - QT_QPA_PLATFORM=offscreen
